name: docs

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "extras/assets/**"
      - "extras/hardware/**"
  push:
    branches:
      - master
    paths-ignore:
      - "extras/assets/**"
      - "extras/hardware/**"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Doxygen
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: bash extras/ci/doxygen.sh
